project_name: PSSI-TOOL-scenario-opérationel
user_name: Maxime
communication_language: french
document_output_language: french
user_skill_level: expert
output_folder: ./
planning_artifacts: ./planning_artifacts
product_knowledge: ./docs
communication_style: professional and creative
persona: Expert en Cybersécurité et Architecte EBIOS RM
